// <auto-generated />
using System;
using HireUp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HireUp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260616081330_test1")]
    partial class test1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HireUp.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HireUp.Entities.AccessibilityNeed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AccessibilityNeed");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Requires company internal tools, software systems, and portals to be fully compatible with software like JAWS, NVDA, or VoiceOver.",
                            Name = "Screen-Reader Compatible Software"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Requires digital documentation, corporate handbooks, and operational dashboards to support dark themes and font size scalability.",
                            Name = "High-Contrast UI & Document Formats"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Prefers business communication, daily updates, and feedback to take place via Slack, Teams, or email rather than audio/video calling.",
                            Name = "Asynchronous Text-First Communication"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Requires all company-wide, all-hands meetings or team syncs to provide real-time automated or manual closed captions.",
                            Name = "Live Meeting Closed-Captioning"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Requires developer environments, corporate web tools, and command interfaces to be fully operational without forcing standard mouse use.",
                            Name = "Keyboard-Only Digital Navigation"
                        },
                        new
                        {
                            Id = 6,
                            Description = "For hybrid roles: Requires step-free physical premises or company-provided ergonomic accessories (e.g., split keyboards, vertical mice, voice-to-text software).",
                            Name = "Accessible Physical Workspace / Ergonomic Equipment"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Requires clear, unambiguous written briefs and ticket documentation rather than loose verbal instructions to optimize workflow execution.",
                            Name = "Explicit, Written Project Requirements"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Requires structural freedom to organize daily focus hours and take micro-breaks to effectively navigate focus and energy variations.",
                            Name = "Flexible Task Breaks & Core Hour Buffers"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Requires the allowance to attend routine medical follow-ups, therapy, or checkups during business hours without formal disciplinary tracking.",
                            Name = "Flexible Medical Appointment Leave"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "019e1f8f-4e4e-7ef2-a8e4-1a78e9919201",
                            ConcurrencyStamp = "019e1f8f-4e4e-7ef2-a8e4-1a798004f0bb",
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Freelancer",
                            NormalizedName = "FREELANCER"
                        },
                        new
                        {
                            Id = "019e1f8f-4e4e-7ef2-a8e4-1a7afe2dcc4f",
                            ConcurrencyStamp = "019e1f8f-4e4e-7ef2-a8e4-1a7bcb3cc53a",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "DisabledFreelancer",
                            NormalizedName = "DISABLEDFREELANCER"
                        },
                        new
                        {
                            Id = "019e1fab-e4a0-7f8e-b3ac-b99c68309f25",
                            ConcurrencyStamp = "019e1fab-e4a0-7f8e-b3ac-b99db5cbc5bc",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Company",
                            NormalizedName = "COMPANY"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("LocationId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "019e1f8f-4e4e-7ef2-a8e4-1a72436e4b44",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "019e1f8f-4e4e-7ef2-a8e4-1a73be063a7f",
                            CreatedAt = new DateTime(2026, 6, 16, 8, 13, 28, 282, DateTimeKind.Utc).AddTicks(249),
                            Email = "Freelancer@Hire-Up.com",
                            EmailConfirmed = true,
                            FirstName = "Freelancer",
                            IsActive = true,
                            LastName = "1",
                            LockoutEnabled = false,
                            NormalizedEmail = "FREELANCER@HIRE-UP.COM",
                            NormalizedUserName = "FREELANCER@HIRE-UP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZKwT+8mydB5fsv8Z/4fPhwJWQWExqwoYln75Yn8aZDGKqX8F5XCMwtgAcm3WSszQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "D2CA77D6E24940FF9BF8408FA0AC6D62",
                            TwoFactorEnabled = false,
                            UserName = "Freelancer@Hire-Up.com"
                        },
                        new
                        {
                            Id = "019e1f8f-4e4e-7ef2-a8e4-1a741a085ba4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "019e1f8f-4e4e-7ef2-a8e4-1a75706084e3",
                            CreatedAt = new DateTime(2026, 6, 16, 8, 13, 28, 282, DateTimeKind.Utc).AddTicks(604),
                            Email = "Disabled-Freelancer@Hire-Up.com",
                            EmailConfirmed = true,
                            FirstName = "Freelancer",
                            IsActive = true,
                            LastName = "Disabled",
                            LockoutEnabled = false,
                            NormalizedEmail = "DISABLED-FREELANCER@HIRE-UP.COM",
                            NormalizedUserName = "DISABLED-FREELANCER@HIRE-UP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZKwT+8mydB5fsv8Z/4fPhwJWQWExqwoYln75Yn8aZDGKqX8F5XCMwtgAcm3WSszQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "746B204025174F4FBF897E51CF10C8AE",
                            TwoFactorEnabled = false,
                            UserName = "Disabled-Freelancer@Hire-Up.com"
                        },
                        new
                        {
                            Id = "019e1f8f-4e4e-7ef2-a8e4-1a761414137c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "019e1f8f-4e4e-7ef2-a8e4-1a777d50816d",
                            CreatedAt = new DateTime(2026, 6, 16, 8, 13, 28, 282, DateTimeKind.Utc).AddTicks(772),
                            Email = "Company@Hire-Up.com",
                            EmailConfirmed = true,
                            FirstName = "Company",
                            IsActive = true,
                            LastName = "Owner",
                            LockoutEnabled = false,
                            NormalizedEmail = "COMPANY@HIRE-UP.COM",
                            NormalizedUserName = "COMPANY@HIRE-UP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZKwT+8mydB5fsv8Z/4fPhwJWQWExqwoYln75Yn8aZDGKqX8F5XCMwtgAcm3WSszQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6CF4145034F9493E8B7540DD827F65CF",
                            TwoFactorEnabled = false,
                            UserName = "Company@Hire-Up.com"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 999999,
                            Name = "Hire Up",
                            UserId = "019e1f8f-4e4e-7ef2-a8e4-1a761414137c"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.DisabilityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DisabilityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Candidates who are blind, have low vision, or experience color-blindness and utilize assistive visual tools or screen modifications.",
                            Name = "Visual Disability"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Candidates who are deaf or hard-of-hearing and rely on written communication channels or captioning frameworks.",
                            Name = "Hearing or Auditory Disability"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Candidates with limited fine motor skills, repetitive strain injuries, or mobility variations requiring ergonomic or alternative physical/digital access.",
                            Name = "Physical or Mobility Disability"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Candidates with ADHD, Autism, Dyslexia, or processing variations who thrive with structured workflows, clear communication, or specialized environments.",
                            Name = "Neurodivergence & Cognitive Variations"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Candidates managing long-term health conditions (e.g., autoimmune, chronic pain) requiring energy management or medical schedule flexibility.",
                            Name = "Chronic Illness or Invisible Disability"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.ExperienceLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ExperienceLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Entry-Level"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Junior"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mid-Level"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Senior"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lead"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.Follows", b =>
                {
                    b.Property<string>("FollowerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("HireUp.Entities.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology & Software"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Design & Creative"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sales & Marketing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Writing & Translation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Finance & Accounting"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Legal & Consulting"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Engineering & Architecture"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Customer Support"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.JobAccessibilityNeed", b =>
                {
                    b.Property<int>("JobListingId")
                        .HasColumnType("int");

                    b.Property<int>("AccessibilityNeedId")
                        .HasColumnType("int");

                    b.HasKey("JobListingId", "AccessibilityNeedId");

                    b.HasIndex("AccessibilityNeedId");

                    b.ToTable("JobAccessibilityNeed");
                });

            modelBuilder.Entity("HireUp.Entities.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobListingId")
                        .HasColumnType("int");

                    b.Property<string>("JobSeekerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobListingId");

                    b.HasIndex("JobSeekerId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("HireUp.Entities.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("JobCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Design"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.JobListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisabilitySupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExperienceLevelId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInclusiveHiring")
                        .HasColumnType("bit");

                    b.Property<int?>("JobCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("OfficeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("ExperienceLevelId");

                    b.HasIndex("JobCategoryId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OfficeTypeId");

                    b.ToTable("JobListings");
                });

            modelBuilder.Entity("HireUp.Entities.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Frontend Developer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Backend Developer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Full Stack Developer"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Digital Marketer"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Content Writer"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.JobType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Contract"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Full-time"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Part-time"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Internship"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Freelance"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Country", "City")
                        .IsUnique();

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Cairo",
                            Country = "Egypt"
                        },
                        new
                        {
                            Id = 2,
                            City = "Alexandria",
                            Country = "Egypt"
                        },
                        new
                        {
                            Id = 3,
                            City = "Riyadh",
                            Country = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 4,
                            City = "Jeddah",
                            Country = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 5,
                            City = "Dubai",
                            Country = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 6,
                            City = "Abu Dhabi",
                            Country = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 7,
                            City = "Amman",
                            Country = "Jordan"
                        },
                        new
                        {
                            Id = 8,
                            City = "Doha",
                            Country = "Qatar"
                        },
                        new
                        {
                            Id = 9,
                            City = "Kuwait City",
                            Country = "Kuwait"
                        },
                        new
                        {
                            Id = 10,
                            City = "Beirut",
                            Country = "Lebanon"
                        },
                        new
                        {
                            Id = 11,
                            City = "Casablanca",
                            Country = "Morocco"
                        },
                        new
                        {
                            Id = 12,
                            City = "Tunis",
                            Country = "Tunisia"
                        },
                        new
                        {
                            Id = 13,
                            City = "Manama",
                            Country = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            City = "New York",
                            Country = "United States"
                        },
                        new
                        {
                            Id = 15,
                            City = "London",
                            Country = "United Kingdom"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.MockInterview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InterviewerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JobSeekerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewerId");

                    b.HasIndex("JobSeekerId");

                    b.ToTable("MockInterviews");
                });

            modelBuilder.Entity("HireUp.Entities.OfficeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OfficeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "On-Site"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Remote"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hybrid"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewedUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("ReviewedUserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("HireUp.Entities.SavedJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobListingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("JobListingId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedJobs");
                });

            modelBuilder.Entity("HireUp.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Backend development",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "Frontend development",
                            Name = "React"
                        },
                        new
                        {
                            Id = 3,
                            Category = 5,
                            Description = "Design Skills",
                            Name = "UI/UX"
                        });
                });

            modelBuilder.Entity("HireUp.Entities.UserAccessibilityNeed", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessibilityNeedId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "AccessibilityNeedId");

                    b.HasIndex("AccessibilityNeedId");

                    b.ToTable("UserAccessibilityNeed");
                });

            modelBuilder.Entity("HireUp.Entities.UserDisabilityType", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DisabilityTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "DisabilityTypeId");

                    b.HasIndex("DisabilityTypeId");

                    b.ToTable("UserDisabilityTypes");
                });

            modelBuilder.Entity("HireUp.Entities.UserJobCategoryPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JobCategoryId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "JobCategoryId");

                    b.HasIndex("JobCategoryId");

                    b.ToTable("UserJobCategoryPreferences");
                });

            modelBuilder.Entity("HireUp.Entities.UserJobTypePreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("OfficeTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "JobTypeId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OfficeTypeId");

                    b.ToTable("UserJobTypePreferences");
                });

            modelBuilder.Entity("HireUp.Entities.UserLocationPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("UserLocationPreferences");
                });

            modelBuilder.Entity("HireUp.Entities.UserOfficeTypePreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OfficeTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "OfficeTypeId");

                    b.HasIndex("OfficeTypeId");

                    b.ToTable("UserOfficeTypePreferences");
                });

            modelBuilder.Entity("JobListingSkills", b =>
                {
                    b.Property<int>("JobListingId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("JobListingId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobListingSkills");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "019e1f8f-4e4e-7ef2-a8e4-1a72436e4b44",
                            RoleId = "019e1f8f-4e4e-7ef2-a8e4-1a78e9919201"
                        },
                        new
                        {
                            UserId = "019e1f8f-4e4e-7ef2-a8e4-1a741a085ba4",
                            RoleId = "019e1f8f-4e4e-7ef2-a8e4-1a7afe2dcc4f"
                        },
                        new
                        {
                            UserId = "019e1f8f-4e4e-7ef2-a8e4-1a761414137c",
                            RoleId = "019e1fab-e4a0-7f8e-b3ac-b99c68309f25"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserSkills", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("HireUp.Entities.ApplicationUser", b =>
                {
                    b.HasOne("HireUp.Entities.JobRole", "JobRole")
                        .WithMany("Users")
                        .HasForeignKey("JobRoleId");

                    b.HasOne("HireUp.Entities.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("HireUp.Entities.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ExpiresOn")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("RevokedOn")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("RefreshTokens", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("JobRole");

                    b.Navigation("Location");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("HireUp.Entities.Company", b =>
                {
                    b.HasOne("HireUp.Entities.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId");

                    b.HasOne("HireUp.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("HireUp.Entities.ApplicationUser", "User")
                        .WithOne("Company")
                        .HasForeignKey("HireUp.Entities.Company", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireUp.Entities.Follows", b =>
                {
                    b.HasOne("HireUp.Entities.ApplicationUser", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("HireUp.Entities.JobAccessibilityNeed", b =>
                {
                    b.HasOne("HireUp.Entities.AccessibilityNeed", "AccessibilityNeed")
                        .WithMany("JobAccessibilityNeeds")
                        .HasForeignKey("AccessibilityNeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.JobListing", "JobListing")
                        .WithMany("JobAccessibilityNeeds")
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessibilityNeed");

                    b.Navigation("JobListing");
                });

            modelBuilder.Entity("HireUp.Entities.JobApplication", b =>
                {
                    b.HasOne("HireUp.Entities.JobListing", "JobListing")
                        .WithMany("Applications")
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "JobSeeker")
                        .WithMany("Applications")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobListing");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("HireUp.Entities.JobListing", b =>
                {
                    b.HasOne("HireUp.Entities.Company", "Company")
                        .WithMany("JobListings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "Employer")
                        .WithMany("JobListings")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ExperienceLevel", "ExperienceLevel")
                        .WithMany("JobListings")
                        .HasForeignKey("ExperienceLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.JobCategory", "JobCategory")
                        .WithMany("JobListings")
                        .HasForeignKey("JobCategoryId");

                    b.HasOne("HireUp.Entities.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.OfficeType", "OfficeType")
                        .WithMany()
                        .HasForeignKey("OfficeTypeId");

                    b.Navigation("Company");

                    b.Navigation("Employer");

                    b.Navigation("ExperienceLevel");

                    b.Navigation("JobCategory");

                    b.Navigation("JobType");

                    b.Navigation("Location");

                    b.Navigation("OfficeType");
                });

            modelBuilder.Entity("HireUp.Entities.MockInterview", b =>
                {
                    b.HasOne("HireUp.Entities.ApplicationUser", "Interviewer")
                        .WithMany("InterviewsAsInterviewer")
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HireUp.Entities.ApplicationUser", "JobSeeker")
                        .WithMany("InterviewsAsSeeker")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interviewer");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("HireUp.Entities.Review", b =>
                {
                    b.HasOne("HireUp.Entities.ApplicationUser", "Author")
                        .WithMany("ReviewsWritten")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.JobApplication", "JobApplication")
                        .WithMany()
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "ReviewedUser")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("ReviewedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("JobApplication");

                    b.Navigation("ReviewedUser");
                });

            modelBuilder.Entity("HireUp.Entities.SavedJob", b =>
                {
                    b.HasOne("HireUp.Entities.JobListing", "JobListing")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "User")
                        .WithMany("SavedJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobListing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireUp.Entities.UserAccessibilityNeed", b =>
                {
                    b.HasOne("HireUp.Entities.AccessibilityNeed", "AccessibilityNeed")
                        .WithMany("UserAccessibilityNeeds")
                        .HasForeignKey("AccessibilityNeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "User")
                        .WithMany("UserAccessibilityNeeds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessibilityNeed");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireUp.Entities.UserDisabilityType", b =>
                {
                    b.HasOne("HireUp.Entities.DisabilityType", "DisabilityType")
                        .WithMany("UserDisabilityTypes")
                        .HasForeignKey("DisabilityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "User")
                        .WithMany("UserDisabilityTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisabilityType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireUp.Entities.UserJobCategoryPreference", b =>
                {
                    b.HasOne("HireUp.Entities.JobCategory", "JobCategory")
                        .WithMany()
                        .HasForeignKey("JobCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "User")
                        .WithMany("UserJobCategoryPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireUp.Entities.UserJobTypePreference", b =>
                {
                    b.HasOne("HireUp.Entities.JobType", "JobType")
                        .WithMany("UserJobTypePreferences")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.Location", null)
                        .WithMany("UserPreferences")
                        .HasForeignKey("LocationId");

                    b.HasOne("HireUp.Entities.OfficeType", null)
                        .WithMany("UserPreferences")
                        .HasForeignKey("OfficeTypeId");

                    b.HasOne("HireUp.Entities.ApplicationUser", "User")
                        .WithMany("UserJobTypePreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireUp.Entities.UserLocationPreference", b =>
                {
                    b.HasOne("HireUp.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "User")
                        .WithMany("UserLocationPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HireUp.Entities.UserOfficeTypePreference", b =>
                {
                    b.HasOne("HireUp.Entities.OfficeType", "OfficeType")
                        .WithMany()
                        .HasForeignKey("OfficeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", "User")
                        .WithMany("UserOfficeTypePreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OfficeType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobListingSkills", b =>
                {
                    b.HasOne("HireUp.Entities.JobListing", null)
                        .WithMany()
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("HireUp.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HireUp.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HireUp.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("HireUp.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HireUp.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserSkills", b =>
                {
                    b.HasOne("HireUp.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HireUp.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HireUp.Entities.AccessibilityNeed", b =>
                {
                    b.Navigation("JobAccessibilityNeeds");

                    b.Navigation("UserAccessibilityNeeds");
                });

            modelBuilder.Entity("HireUp.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Company");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("InterviewsAsInterviewer");

                    b.Navigation("InterviewsAsSeeker");

                    b.Navigation("JobListings");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("ReviewsWritten");

                    b.Navigation("SavedJobs");

                    b.Navigation("UserAccessibilityNeeds");

                    b.Navigation("UserDisabilityTypes");

                    b.Navigation("UserJobCategoryPreferences");

                    b.Navigation("UserJobTypePreferences");

                    b.Navigation("UserLocationPreferences");

                    b.Navigation("UserOfficeTypePreferences");
                });

            modelBuilder.Entity("HireUp.Entities.Company", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("HireUp.Entities.DisabilityType", b =>
                {
                    b.Navigation("UserDisabilityTypes");
                });

            modelBuilder.Entity("HireUp.Entities.ExperienceLevel", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("HireUp.Entities.Industry", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("HireUp.Entities.JobCategory", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("HireUp.Entities.JobListing", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobAccessibilityNeeds");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("HireUp.Entities.JobRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HireUp.Entities.JobType", b =>
                {
                    b.Navigation("UserJobTypePreferences");
                });

            modelBuilder.Entity("HireUp.Entities.Location", b =>
                {
                    b.Navigation("UserPreferences");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("HireUp.Entities.OfficeType", b =>
                {
                    b.Navigation("UserPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
